default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: viethieu123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: railsTutorial_development

test:
  <<: *default
  database: railsTutorial_test

production:
  <<: *default
  database: railsTutorial_production
  username: railsTutorial
  password: <%= ENV['RAILSTUTORIAL_DATABASE_PASSWORD'] %>
